# Generated by Django 4.2.6 on 2024-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='scrap_pic',
            field=models.ImageField(null=True, upload_to='scrap'),
        ),
    ]
