# Generated by Django 4.2.6 on 2024-02-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0002_alter_scraps_scrap_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
