# Generated by Django 4.2.6 on 2024-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbox', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='status',
            field=models.CharField(choices=[('Sold', 'sold'), ('Available', 'available')], default='Available', max_length=200),
        ),
    ]
